### ISSUE TITLE
[Typo/Bug] ttp://www.geneontology.org/formats/oboInOwl#created_by

### ISSUE THREAD

**Issue by acevedol** [obophenotype/caro#36]
**CL term**
`ttp://www.geneontology.org/formats/oboInOwl#created_by`

**Description of typo, bug or error**

Came across a typo in the cell ontology: `ttp://www.geneontology.org/formats/oboInOwl#created_by`

**Comment by shawntanzk** [comment]
@anitacaron - could you help with this small fix please? :D thankssssss
